default:
  data:
    IHC:
        GluD2_path: !expr here::here("data", "IHC", "GluD2.xlsx")
        vglut_path: !expr here::here("data", "IHC", "vglut.xlsx")
        mbp_path: !expr here::here("data", "IHC", "MBP.xlsx")
        casp_P12_path: !expr here::here("data", "IHC", "Casp_P12.xlsx")
        calb_P12_path: !expr here::here("data", "IHC", "Calb_P12.xlsx")
        calb_P21_path: !expr here::here("data", "IHC", "Calb_P21.xlsx")
        brDU_path: !expr here::here("data", "IHC", "BrDU.xlsx")
        dapi_ml_ad_path: !expr here::here("data", "IHC", "DAPI_ML_Adult.xlsx")
        dapi_density_P12_path: !expr here::here("data", "IHC", "DAPI_Density_P12.xlsx")
        casp_Act_path: !expr here::here("data", "IHC", "Casp3_raw_long.xlsx")
        weight_path: !expr here::here("data", "IHC", "Weight.xlsx")
        behavior_pups_path: !expr here::here("data", "IHC", "Behavior_Pups_Long.xlsx")
        behavior_teens_path: !expr here::here("data", "IHC", "Behavior_Teens_Long.xlsx")
        behavior_adults_path: !expr here::here("data", "IHC", "Behavior_Adults_Long.xlsx")
        thickness_path: !expr here::here("data", "IHC", "Thickness.xlsx")
        ROS_path: !expr here::here("data", "IHC", "ROS_Percentage.xlsx")
    PCR:
        OS_P12_path: !expr here::here("data", "PCR", "Data_OS_P12.xlsx")
        mouse_info_path: !expr here::here("data", "PCR", "Mouse_info.xlsx")
        pathways_info_path: !expr here::here("data", "PCR", "Pathways_info.xlsx")
