# Foreword {.unnumbered}

This website serves as documentation as well as to showcase the data and R analysis code for *(Leroux S., Rodriguez-Duboc A., Arabo A., Basille-Dugay M., Vaudry D., & Burel D., 2022)* paper:

::: {.callout-tip appearance="simple" icon=false}
## Intermittent hypoxia in a mouse model of apnea of prematurity leads to a retardation of cerebellar development and long-term functional deficits
:::

## Structure of this website

Each of the files listed in the navigation bar (left side of the screen) contains multiple variables that we analyzed, grouped by thematic. Each file will contain a section for each of those variables. Each of those sections is further divided into three subsections:  

1) `Data Exploration`: variable's summary statistics, distribution, and evolution in time *(if applicable)*.  

2) `Models & Diagnostics`: quality of fit, diagnostics and predictions for each of the candidate models of that variable.

:::{.column-margin}
:::{.callout-note appearance="simple"}
Each candidate model is split in its own tab.
:::
:::

:::{.callout-important}

### Disclaimer on the presence of multiple models

We chose to (sometimes) display several candidate models for each variable of interest for the sake of exploration. However, the model we ended up using for testing our hypotheses was picked mainly based on theoretical criteria, and not through significance testing (to avoid losses of generalizability). The overall quality of fit of each candidate model was also taken into account in that decision, through the use of residuals and predictive plots.
:::


3) `Effects Analysis`: the chosen model's coefficients, main effects (Wald $\chi^2$ and Likelihood Ratio Test), and the marginal means and contrasts for each of its predictor. This subsection also includes the box plots showcased in the article.

:::{.column-margin}
:::{.callout-note appearance="simple"}
Each variable is split in its own tab.
:::
:::

:::{.callout-important}

### Disclaimer on multiple testing

For the sake of exploration and transparency, we showcase the marginal means and contrasts for all the predictors (and interactions) of the chosen model. However, only a subset of those contrasts were of interest during the study (viz. mainly the impact of `Condition`, i.e. whether the mouse was submitted to Intermittent Hypoxia or not). Many of those contrasts were thus not included in the paper, not because they were not significant, but because they were not of interest to the authors.
:::