# DAPI

*Di-Amidino-2-Phenyl-Indole*

```{r}
#| echo: false
#| output: false

source(here::here("src", "init.R"), echo = FALSE)
```

```{r}
#| echo: false

data <- load_dapi_ml_ad(config$data$dapi_ml_ad_path)

responses <- c("A_ML", "A_DAPI", "Vol_DAPI")
predictors <- c("Condition", "Z")

data_agg <- (data
  |> group_by(Mouse, Condition) 
  |> summarize(across(matches(responses), .fns = \(.x) mean(.x, na.rm = T))) 
  |> ungroup() 
  |> mutate(dCondition = as.numeric(Condition == "IH")) 
  |> rowid_to_column("ID")
)

contrasts(data$Condition) <- contr.sum
contrasts(data$Z) <- contr.sum

### Variables:

A_ML_name <- "Molecular layer area *(10^(-4) μm^(2))*"
A_DAPI_name <- "Area marked with DAPI *(10^(-4) μm^(2))*"
Vol_DAPI_name <- "Volume of DAPI marking *(10^(-4) μm^(3))*"
```

❖ **Data**

```{r}
#| echo: false

n_samp <- 15

kable_html(data |> head(n_samp))
```

(*Sample of `r n_samp` data points*)

❖ **Correlations**

```{r}
#| echo: false
#| fig.width: 8

corr_matrix_plot(data, vars = c(c(predictors, "Mouse"), responses))
```


## Molecular layer area

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(A_ML ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(A_ML ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```


## Volume of DAPI marking

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(A_DAPI ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(A_DAPI ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)

template_output <- knitr::knit_child(config$templates$base, quiet = TRUE)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```


## Area marked with DAPI

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(Vol_DAPI ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(Vol_DAPI ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```