# Gluδ2 Parallel Fibers

```{r}
#| echo: false
#| output: false

source(here::here("src", "init.R"), echo = FALSE)
```

```{r}
#| echo: false

responses <- c("A_DD", "A_DD_per_cell", "A_GLUD2", "Vol_GLUD2")
predictors <- c("Condition", "Z")

data <- load_GluD2(config$data$GluD2_path) |> select(Sample, Mouse, any_of(predictors), any_of(responses))

data_agg <- (data
  |> group_by(Mouse, Condition) 
  |> summarize(across(matches(responses), .fns = \(.x) mean(.x, na.rm = T))) 
  |> ungroup() 
  |> mutate(dCondition = as.numeric(Condition == "IH")) 
  |> rowid_to_column("ID")
)

contrasts(data$Condition) <- contr.sum
contrasts(data$Z) <- contr.sum

### Variables:

A_GLUD2_name <- "Gluδ2-labelled Parallel fiber area  \n in the ML *(10^(-5) μm^(2))*"
Vol_GLUD2_name  <- "Gluδ2-labelled Parallel fiber volume  \n in the ML *(10^(-5) μm^(3))*"

A_DD_name  <- "Purkinje dendrite area *(10^(-4) μm^(2))*"
A_DD_per_cell_name  <- "Purkinje dendrite area *(10^(-4) μm^(2))*  \n per Purkinje cell"
```

❖ **Data**

```{r}
#| echo: false
#| output: asis

n_samp <- 15

gt(data |> head(n_samp))
```

(*Sample of `r n_samp` data points*)

❖ **Correlations**

```{r}
#| echo: false
#| output: asis
#| fig.width: 8

corr_matrix_plot(data, vars = c(c(predictors, "Mouse"), responses))
```


## Purkinje Dendrite Area (per cell)

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(A_DD_per_cell ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(A_DD_per_cell ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```


## Gluδ2-labelled Parallel fiber Area in the ML

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(A_GLUD2 ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(A_GLUD2 ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```


## Gluδ2-labelled Parallel fiber Volume in the ML

```{r}
#| echo: false

## WARN: Always put the chosen model in first position
models <- list(
  glmmTMB(Vol_GLUD2 ~ Condition * Z + (1 | Mouse), family = Gamma("log"), data = data, REML = TRUE), 
  glmmTMB(Vol_GLUD2 ~ Condition * Z + (1 | Mouse), family = gaussian("log"), data = data, REML = TRUE)
)
```

```{r}
#| echo: false
#| output: asis

knitr::knit_child(config$templates$base, quiet = TRUE) |> unlist() |> cat(sep = '\n')
```